export const CLICK_SUCCESS = 'CLICK_SUCCESS'
export const CLICK_REQUEST = 'CLICK_REQUEST'
export const CLICK_FAILURE = 'CLICK_FAILURE'

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const PERSIST_TOKEN = 'persist/REHYDRATE'
